export default {
  2114954: {
    activityLog: [
      {
        type: 'service',
        time: '2018-09-10 13:10:09',
        action: 'Created account',
        amount: 10000,
        touchpoint: 'Mobile App',
        branch: 'Kencom',
        icon: 'account_balance',
      },
      {
        type: 'transaction',
        time: '2018-09-10 13:30:10',
        action: 'Deposited',
        amount: 40000,
        touchpoint: 'Mpesa',
        branch: null,
        icon: 'arrow_upward',
      },
      {
        type: 'transaction',
        time: '2018-09-15 10:10:09',
        action: 'Loaned',
        amount: 10000,
        touchpoint: 'Mpesa',
        branch: null,
        icon: 'arrow_upward',
      },
      {
        type: 'transaction',
        time: '2018-10-30 13:10:09',
        action: 'Deposited',
        amount: 150000,
        touchpoint: null,
        branch: 'Kencom',
        icon: 'arrow_upward',
      },
      {
        type: 'service',
        time: '2018-10-30 13:10:09',
        action: 'Completed NPS survey',
        amount: 150000,
        touchpoint: 'teller services touchpoint',
        branch: null,
        icon: 'message',
      },
      {
        type: 'service',
        time: '2018-10-30 13:10:09',
        action: 'Installed KCB mobile app on Android',
        amount: 10000,
        touchpoint: 'Google Play store',
        branch: null,
        icon: 'smartphone',
      },
      {
        type: 'transaction',
        time: '2018-11-01 13:10:09',
        action: 'Loaned',
        amount: 10000,
        touchpoint: 'Mobile App',
        branch: null,
        icon: 'account_balance_wallet',
      },
      {
        type: 'service',
        time: '2018-11-05 13:10:09',
        action: 'Applied for ATM card',
        amount: null,
        touchpoint: null,
        branch: 'Kasarani',
        icon: 'credit_card',
      },
      {
        type: 'service',
        time: '2018-11-05 14:10:09',
        action: 'Completed NPS survey',
        amount: 150000,
        touchpoint: 'ATM services touchpoint',
        branch: null,
        icon: 'message',
      },
      {
        type: 'transaction',
        time: '2018-11-10 13:10:09',
        action: 'Loaned',
        amount: 10000,
        touchpoint: 'Mobile App',
        branch: null,
        icon: 'account_balance_wallet',
      },
      {
        type: 'transaction',
        time: '2018-11-11 13:10:09',
        action: 'Paid loan',
        amount: 20000,
        touchpoint: 'Mpesa',
        branch: null,
        icon: 'account_balance_wallet',
      },
      {
        type: 'transaction',
        time: '2018-11-15 13:10:09',
        action: 'Withdrew',
        amount: 50000,
        touchpoint: 'ATM',
        branch: null,
        icon: 'arrow_downward',
      },
      {
        type: 'transaction',
        time: '2018-11-16 13:10:09',
        action: 'Sent',
        amount: 40000,
        touchpoint: 'RTGS',
        branch: null,
        icon: 'arrow_downward',
      },
      {
        type: 'transaction',
        time: '2018-11-20 13:10:09',
        action: 'Deposited',
        amount: 100000,
        touchpoint: 'Mpesa',
        branch: null,
        icon: 'arrow_upward',
      },
      {
        type: 'transaction',
        time: '2018-12-01 13:10:09',
        action: 'Deposited',
        amount: 60000,
        touchpoint: 'Mpesa',
        branch: null,
        icon: 'arrow_upward',
      },
      {
        type: 'transaction',
        time: '2018-12-02 13:10:09',
        action: 'Bought airtime',
        amount: 1000,
        touchpoint: 'Mobile App',
        branch: null,
        icon: 'arrow_downward',
      },
      {
        type: 'transaction',
        time: '2018-12-05 13:10:09',
        action: 'Deposited',
        amount: 30000,
        touchpoint: 'Mpesa',
        branch: null,
        icon: 'arrow_upward',
      },
      {
        type: 'transaction',
        time: '2018-12-09 13:10:09',
        action: 'Deposited',
        amount: 12000,
        touchpoint: 'Mpesa',
        branch: null,
        icon: 'arrow_upward',
      },
    ],
  },
};
