export const SET_AOD_DATA = 'SET_AOD_DATA';
export const SET_SURVEY_DATA_TABLE = 'SET_SURVEY_DATA_TABLE';
export const CLEAR_AOD_REPORTS = 'CLEAR_AOD_REPORTS';
export const SET_SURVEY_QUESTIONS = 'SET_SURVEY_QUESTIONS';
