export default [{
  app: 'home',
  label: 'Home',
  icon: 'home',
  paths: ['/'],
  showRightDrawer: true,
  fullWidthMenu: true,
}, {
  app: 'surveys',
  label: 'Surveys',
  icon: 'smartphone',
  paths: ['/surveys'],
  showRightDrawer: true,
  fullWidthMenu: true,
},
// {
//   app: 'live-chat',
//   label: 'Live Chat',
//   icon: 'sms',
//   paths: ['/live-chat', '/live-chat/:activeParticipantConversationId?'],
//   showRightDrawer: false,
//   fullWidthMenu: false,
// },
{
  app: 'customers',
  label: 'Customers',
  icon: 'group',
  paths: ['/customers'],
  showRightDrawer: false,
  fullWidthMenu: true,
  // sublinks: [{
  //   label: 'All Customers',
  //   path: '/customers/list',
  //   level: 0,
  // }, {
  //   label: 'Segments',
  //   path: '/customers/segments',
  //   level: 0,
  // }],
}, {
  app: 'analytics',
  label: 'Analytics',
  icon: 'show_chart',
  paths: ['/analytics'],
  showRightDrawer: false,
  fullWidthMenu: true,
  sublinks: [{
    label: 'Loyalty & Satisfaction',
    path: '/analytics/loyalty-satisfaction',
    level: 0,
    sublinks: [{
      icon: 'view_stream',
      label: 'Customers',
      path: '/customers',
      level: 1,
    }],
  }, {
    icon: 'whatshot',
    label: 'Behavior',
    path: '/analytics/behaviour',
    level: 0,
    sublinks: [{
      icon: 'view_stream',
      label: 'Customers',
      path: '/customers',
      level: 1,
    }],
  }, {
    icon: 'show_chart',
    label: 'Spend',
    path: '/analytics/spend',
    level: 0,
    sublinks: [{
      icon: 'view_stream',
      label: 'Customers',
      path: '/customers',
      level: 1,
    }],
  }, {
    icon: 'map',
    label: 'Demographics',
    path: '/analytics/demographic',
    level: 0,
  }],
},
{
  app: 'settings',
  label: 'Settings',
  icon: 'settings',
  paths: ['/settings'],
  showRightDrawer: false,
  fullWidthMenu: true,
  sublinks: [{
    label: 'Item',
    path: '/settings/item',
    level: 0,
  }, {
    label: 'Item',
    path: '/settings/item',
    level: 0,
  }, {
    label: 'Item',
    path: '/settings/item',
    level: 0,
  }],
},
];
