export const SET_SEGMENTS = 'SET_SEGMENTS';
export const SET_FILTERS = 'SET_FILTERS';
export const SET_APPLIED_FILTERS = 'SET_APPLIED_FILTERS';
export const CLEAR_APPLIED_FILTERS = 'CLEAR_APPLIED_FILTERS';
