export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';
export const ADD_NEW_CONVERSATION = 'ADD_NEW_CONVERSATION';
export const SET_MORE_CONVERSATIONS = 'SET_MORE_CONVERSATIONS';
export const GET_CONVERSATION = 'SET_CONVERSATIONS';
export const REPLY_IN_CONVERSATION = 'REPLY_IN_CONVERSATION';
export const RESET_UNREAD_MESSAGES_COUNT = 'RESET_UNREAD_MESSAGES_COUNT';
export const UNMOUNT_CONVERSATIONS = 'UNMOUNT_CONVERSATIONS';
