export const ADD_AUDIENCE = 'ADD_AUDIENCE';
export const ADD_AUDIENCES = 'ADD_AUDIENCES';
export const UPDATE_AUDIENCE = 'UPDATE_AUDIENCE';
export const REMOVE_AUDIENCE = 'REMOVE_AUDIENCE';
export const REMOVE_AUDIENCES = 'REMOVE_AUDIENCES';
export const SET_AUDIENCES = 'SET_AUDIENCES';
