export const SET_AOD_DATA = 'SET_AOD_DATA';
export const SET_SURVEY_DATA_TABLE = 'SET_SURVEY_DATA_TABLE';
export const CLEAR_CS_REPORTS = 'CLEAR_CS_REPORTS';
export const SET_NPS_METADATA_FILTERS = 'SET_NPS_METADATA_FILTERS';
export const SET_SURVEY_QUESTIONS = 'SET_SURVEY_QUESTIONS';
