export const SET_ROUTE_TITLE = 'SET_ROUTE_TITLE';
export const UNSET_ROUTE_TITLE = 'UNSET_ROUTE_TITLE';
export const SET_APP_NAME = 'SET_APP_NAME';
export const SET_BEFORE_INSTALL_PROMPT_FIRE = 'SET_BEFORE_INSTALL_PROMPT_FIRE';
