export default {
  1: 'ABC',
  2: 'Aero Club',
  3: 'Aga Khan',
  4: 'Airport View',
  5: 'Airside',
  6: 'CAPITAL',
  7: 'Ciata Mall',
  8: 'CITY HALL',
  9: 'COFFEE SALES',
  10: 'Commissary',
  11: 'Diani',
  12: 'DOWNTOWN',
  13: 'ELDORET',
  14: 'Embassy House',
  15: 'GALLERIA',
  16: 'GARDEN CITY',
  17: 'GIGIRI',
  18: 'GREEENSPAN',
  19: 'HURLINGAM',
  20: 'Java Southfield',
  21: 'JUNCTION',
  22: 'Karen',
  23: 'Kenya Re',
  24: 'KERICHO',
  25: 'Kileleshwa',
  26: 'KIMATHI',
  27: 'KISUMU',
  28: 'KMA',
  29: 'LANDSIDE',
  30: 'Lenana Road',
  31: 'LUNGA LUNGA',
  32: 'Monrovia Street',
  33: 'NAIVASHA',
  34: 'NAKURU CBD',
  35: 'NAKURU WESTSIDE',
  36: 'Nanyuki',
  37: 'NYALI',
  38: 'Nyali',
  39: 'ORBIT',
  40: 'OUTSIDE CATERING',
  41: 'PARKLANDS',
  42: 'PHOENIX',
  43: 'PRESTIGE PLAZA',
  44: 'ROSSLYN',
  45: 'SARIT',
  46: 'SOUTH C',
  47: 'TERMINAL 2',
  48: 'TRM',
  49: 'UNIAFRIC',
  50: 'UPPERHILL',
  51: 'USIU',
  52: 'V/ARCADE',
  53: 'WAIYAKI WAY',
  54: 'WEST END',
  55: 'WESTLANDS SQUARE',
  56: 'YAYA',
  57: 'ADAMS',
};
