export const ADD_COLLABORATORS = 'ADD_COLLABORATORS';
export const REMOVE_COLLABORATORS = 'REMOVE_COLLABORATORS';
export const REMOVE_COLLABORATOR = 'REMOVE_COLLABORATOR';
export const UPDATE_COLLABORATOR = 'UPDATE_COLLABORATOR';
