export const SET_ACCOUNT_CONFIGURATIONS = 'SET_ACCOUNT_CONFIGURATIONS';
export const UPDATE_IS_FETCHING_CONFIGURATIONS_STATUS = 'UPDATE_IS_FETCHING_CONFIGURATIONS_STATUS';
export const UPDATE_FETCH_CONFIGURATION_ERROR_STATUS = 'UPDATE_FETCH_CONFIGURATION_ERROR_STATUS';
export const UPDATE_DEMO_MODE = 'UPDATE_DEMO_MODE';
